version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Build phase complete!"

  post_build:
    commands:
      - echo "Deploying app..."

artifacts:
  files:
    - server.py